workflows:
  expo-android:
    name: Expo Android Build 
    max_build_duration: 60
    triggering:
      events:
      - push
      branch_patterns:
      - pattern: "main"
        include: true
        source: true
      cancel_previous_builds: true
    environment:
      vars:
        NODE_VERSION: 18
        JAVA_VERSION: 17
        GRADLE_OPTS: -Xmx4g
      android_signing:
        - iamsameer
    cache:
        cache_paths:
          - ~/.npm
          - ~/.gradle
    scripts:
      - name: Clean previous Android build
        script: |
          rm -rf android/app/build
      - name: Prebuild Expo
        script: |
          npx expo prebuild --platform android --clean

      - name: Install dependencies
        script: |
          LOCK_HASH=$(sha256sum package-lock.json | cut -d' ' -f1)
          if [ -d node_modules ] && [ "$LOCK_HASH" = "$(cat .lock.hash 2>/dev/null)" ]; then
            echo "📦 Dependencies unchanged, using cache"
          else
            echo "📦 Installing dependencies..."
            npm ci
            echo "$LOCK_HASH" > .lock.hash
          fi
      - name: Build Android release
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
    artifacts:
    - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - strangeisnoone@gmail.com
          - paudelsameer888@gmail.com
        notify:
          success: true
          failure: true